config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/bienvenida", to: "home#index"

  root to: "home#index"

  get "articles", to: "articles#index"
  get "articles/new", to: "articles#new", as: :new_articles
  get "articles/:id", to: "articles#show"
  get "articles/:id/edit", to: "articles#edit"
  patch "articles/:id", to: "articles#update", as: :article
  post "articles", to: "articles#create"
  delete "articles/:id", to:"articles#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_rich_text :content
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :find_article, except: [:new,:create,:index]
    
    def index
    @article = Article.all
    end
    
    
    def show 
    end     
    
    def edit
    end
    
    def update
        @article.update(title: params[:article][:title], content: params[:article] [:content])
        
        redirect_to @article
    end

    def new
        @article = Article.new
        @article.title = "Demo"
    end

    def create 
        render json: @article
    end

    def destroy
        @article.destroy
        redirect_to root_path
    end 
    
    def find_article
        @article = Article.find (params[:id]) 
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_article.htm.erb
<div> class="card padding margin-top">
<h3 class="text-uppercase"><%= article.title %></h3>
<p class="text-secondary"><%= article.created_at %></p>
<%= link_to "Ver mas",article %>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: @article, local: true) do |form| %>

    <div class="field>"
        <%=form.label :title %>
        <%=form.text_field :title %>
    </div>

    <div class="field>"
        <%=form.label :content %>
        <%=form.rich_text_area :content %>
    </div>

    <div>
        <%= form.submit %>
    </div>
<%end%>

app/views/articles/edit.html.erb
<div class"samll-container center-block">

    <%= render "articles/form" %>
</div>

app/views/articles/index.html.erb
<div class="large-container center-block">
<h1>Mis articulos</h1>

<% render @articles %>
</div>

  

app/views/articles/new.html.erb
<div class"samll-container center-block">

    <%= render "articles/form" %>
</div>

app/views/articles/show.html.erb
<%= render "partials/nav" %>

<h1><%=@article.title%></h1>

    <div> 
        <%= @article.content %>
    </div>
    end

    <div>
        <%=link_to "eliminar el articulo", @article, method: delete %>
    </div>
    end 
end

app/views/home/index.html.erb
<h1>Hola mundo :) </h1>

<%=link_to "Inicio", root_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogM9</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if true %>
     <p class="alert alert-primary"><%= notice %></p>
    <%end%>
    <% if true %>
      <p class="alert alert-danger"><%= alert %></p>
    <%end%>
      <%= render "partials/nav" %>
    <%= yield %>
  </body>
</html>

app/views/partials/_nav.html.erb
<nav class="nav bg-light padding">
    <li class="nav-item">    
        <%=link_to "Inicio", root_path, class:"nav-link" %>
    </li>
    <li class="nav-item">    
        <%=link_to "Articulos", articles_path, class:"nav-link" %>
    </li>
    <li class="nav-item">    
        <%=link_to "Ecribir", new_articles_path, class:"nav-link" %>
    </li>
</nav>